name: CI

on: [push, pull_request]

jobs:
  appimage-build:
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x86_64, i386]

    name: AppImage ${{ matrix.ARCH }}
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.ARCH }}
      DIST: bionic
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build AppImage in Docker
        run: bash -ex ci/build-in-docker.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage build ${{ matrix.ARCH }}
          path: |
            AppImageUpdate*.AppImage*
            appimageupdatetool*.AppImage*
            validate*.AppImage*

      - name: Upload build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: true
          title: "Continuous Build"
          files: |
           AppImageUpdate*.AppImage*
           appimageupdatetool*.AppImage*
           validate*.AppImage*
